########################################################################################

# This Makefile generated by GoMakeGen 0.6.0 using next command:
# gomakegen .

########################################################################################

.PHONY = fmt all clean deps

########################################################################################

all: bastion

bastion:
	go build bastion.go

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v github.com/valyala/fasthttp
	go get -d -v pkg.re/essentialkaos/ek.v9

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

clean:
	rm -f bastion

########################################################################################
