########################################################################################

# This Makefile generated by GoMakeGen 0.6.0 using next command:
# gomakegen --metalinter .

########################################################################################

.PHONY = fmt all clean deps metalinter

########################################################################################

all: bastion

bastion:
	go build bastion.go

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v github.com/valyala/fasthttp
	go get -d -v golang.org/x/crypto/bcrypt
	go get -d -v golang.org/x/crypto/blowfish
	go get -d -v pkg.re/essentialkaos/ek.v9

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

metalinter:
	test -s $(GOPATH)/bin/gometalinter || (go get -u github.com/alecthomas/gometalinter ; $(GOPATH)/bin/gometalinter --install)
	$(GOPATH)/bin/gometalinter --deadline 30s

clean:
	rm -f bastion

########################################################################################
